{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPnq1spKgcYCX+Ujk6v5L/w",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/Attri-Niharika/CEI-Assignments/blob/main/week7_niharika.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 385
        },
        "id": "_XiW5BHrqqM_",
        "outputId": "bc446e09-7cfe-4c96-e740-ad92336db450"
      },
      "outputs": [
        {
          "output_type": "error",
          "ename": "ModuleNotFoundError",
          "evalue": "No module named 'langchain_community'",
          "traceback": [
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
            "\u001b[0;32m/tmp/ipykernel_2590/3330311230.py\u001b[0m in \u001b[0;36m<cell line: 0>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mtyping\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mList\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mOptional\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      6\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 7\u001b[0;31m \u001b[0;32mfrom\u001b[0m \u001b[0mlangchain_community\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdocument_loaders\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mPyPDFLoader\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mTextLoader\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      8\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mlangchain_text_splitters\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mRecursiveCharacterTextSplitter\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      9\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mlangchain_ollama\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mChatOllama\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
            "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'langchain_community'",
            "",
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0;32m\nNOTE: If your import is failing due to a missing package, you can\nmanually install dependencies using either !pip or !apt.\n\nTo view examples of installing some common dependencies, click the\n\"Open Examples\" button below.\n\u001b[0;31m---------------------------------------------------------------------------\u001b[0m\n"
          ],
          "errorDetails": {
            "actions": [
              {
                "action": "open_url",
                "actionText": "Open Examples",
                "url": "/notebooks/snippets/importing_libraries.ipynb"
              }
            ]
          }
        }
      ],
      "source": [
        "import os\n",
        "import sys\n",
        "import glob\n",
        "from pathlib import Path\n",
        "from typing import List, Optional\n",
        "\n",
        "from langchain_community.document_loaders import PyPDFLoader, TextLoader\n",
        "from langchain_text_splitters import RecursiveCharacterTextSplitter\n",
        "from langchain_ollama import ChatOllama\n",
        "from langchain_huggingface import HuggingFaceEmbeddings\n",
        "from langchain_chroma import Chroma\n",
        "from langchain_core.documents import Document\n",
        "from langchain_core.prompts import ChatPromptTemplate\n",
        "from langchain_core.runnables import RunnablePassthrough\n",
        "from langchain_core.output_parsers import StrOutputParser\n",
        "\n",
        "\n",
        "CHROMA_DIR = Path(\"chroma_db\")\n",
        "OLLAMA_BASE_URL = \"http://localhost:11434\"\n",
        "EMBED_MODEL = \"sentence-transformers/all-MiniLM-L6-v2\"\n",
        "LLM_MODEL = \"llama3.2:3b\"\n",
        "CHUNK_SIZE = 500\n",
        "CHUNK_OVERLAP = 50\n",
        "\n",
        "\n",
        "def load_documents(data_dir: str) -> List[Document]:\n",
        "    docs = []\n",
        "    data_path = Path(data_dir)\n",
        "    if not data_path.exists():\n",
        "        print(f\"Error: directory '{data_dir}' not found\")\n",
        "        sys.exit(1)\n",
        "\n",
        "    pdf_files = list(data_path.glob(\"**/*.pdf\"))\n",
        "    txt_files = list(data_path.glob(\"**/*.txt\"))\n",
        "\n",
        "    for fp in pdf_files:\n",
        "        loader = PyPDFLoader(str(fp))\n",
        "        docs.extend(loader.load())\n",
        "\n",
        "    for fp in txt_files:\n",
        "        loader = TextLoader(str(fp), encoding=\"utf-8\")\n",
        "        docs.extend(loader.load())\n",
        "\n",
        "    if not docs:\n",
        "        print(f\"No PDF or TXT files found in '{data_dir}'\")\n",
        "        sys.exit(1)\n",
        "\n",
        "    print(f\"Loaded {len(docs)} document(s)\")\n",
        "    return docs\n",
        "\n",
        "\n",
        "def chunk_documents(docs: List[Document]) -> List[Document]:\n",
        "    splitter = RecursiveCharacterTextSplitter(\n",
        "        chunk_size=CHUNK_SIZE,\n",
        "        chunk_overlap=CHUNK_OVERLAP,\n",
        "        separators=[\"\\n\\n\", \"\\n\", \". \"],\n",
        "    )\n",
        "    chunks = splitter.split_documents(docs)\n",
        "    print(f\"Split into {len(chunks)} chunks\")\n",
        "    return chunks\n",
        "\n",
        "\n",
        "class RAGSystem:\n",
        "    def __init__(self, force_reindex: bool = False, debug: bool = False):\n",
        "        self.embeddings = HuggingFaceEmbeddings(\n",
        "            model_name=EMBED_MODEL,\n",
        "        )\n",
        "        self.llm = ChatOllama(\n",
        "            model=LLM_MODEL,\n",
        "            base_url=OLLAMA_BASE_URL,\n",
        "            temperature=0.1,\n",
        "        )\n",
        "        self.vector_store = None\n",
        "        self.retriever = None\n",
        "        self.force_reindex = force_reindex\n",
        "        self.debug = debug\n",
        "\n",
        "    def index_documents(self, data_dir: str) -> None:\n",
        "        if CHROMA_DIR.exists() and not self.force_reindex:\n",
        "            print(\"Loading existing vector store...\")\n",
        "            self.vector_store = Chroma(\n",
        "                persist_directory=str(CHROMA_DIR),\n",
        "                embedding_function=self.embeddings,\n",
        "            )\n",
        "            self.retriever = self.vector_store.as_retriever(search_kwargs={\"k\": 4})\n",
        "            print(f\"Vector store loaded ({CHROMA_DIR})\")\n",
        "            return\n",
        "\n",
        "        docs = load_documents(data_dir)\n",
        "        chunks = chunk_documents(docs)\n",
        "\n",
        "        print(\"Creating embeddings and building vector store...\")\n",
        "        self.vector_store = Chroma.from_documents(\n",
        "            documents=chunks,\n",
        "            embedding=self.embeddings,\n",
        "            persist_directory=str(CHROMA_DIR),\n",
        "        )\n",
        "        self.retriever = self.vector_store.as_retriever(search_kwargs={\"k\": 4})\n",
        "        print(f\"Vector store created with {len(chunks)} chunks\")\n",
        "\n",
        "    def query(self, question: str) -> str:\n",
        "        if self.retriever is None:\n",
        "            return \"Error: No documents indexed. Call index_documents() first.\"\n",
        "\n",
        "        retrieved_docs = self.retriever.invoke(question)\n",
        "\n",
        "        if self.debug:\n",
        "            print(\"\\n--- Retrieved Contexts ---\")\n",
        "            for i, d in enumerate(retrieved_docs):\n",
        "                src = d.metadata.get(\"source\", \"unknown\")\n",
        "                print(f\"[{i+1}] (from {src}):\\n{d.page_content[:200]}...\\n\")\n",
        "            print(\"--- End Contexts ---\\n\")\n",
        "\n",
        "        context = \"\\n\\n\".join(d.page_content for d in retrieved_docs)\n",
        "\n",
        "        prompt = ChatPromptTemplate.from_messages([\n",
        "            (\n",
        "                \"system\",\n",
        "                \"You are a helpful assistant. Answer the question using ONLY the context below. \"\n",
        "                \"If the context does not contain the answer, say \\\"I cannot find this in the provided documents.\\\" \"\n",
        "                \"Do not use your own knowledge. Be concise.\",\n",
        "            ),\n",
        "            (\n",
        "                \"human\",\n",
        "                \"Context:\\n{context}\\n\\nQuestion: {question}\\n\\nAnswer:\",\n",
        "            ),\n",
        "        ])\n",
        "\n",
        "        chain = (\n",
        "            {\"context\": lambda _: context, \"question\": RunnablePassthrough()}\n",
        "            | prompt\n",
        "            | self.llm\n",
        "            | StrOutputParser()\n",
        "        )\n",
        "\n",
        "        return chain.invoke(question)\n",
        "\n",
        "    def interactive(self) -> None:\n",
        "        print(\"\\n\" + \"=\" * 60)\n",
        "        print(\"  RAG Question Answering System\")\n",
        "        print(\"  Type 'quit' or 'exit' to stop\")\n",
        "        print(\"=\" * 60)\n",
        "        while True:\n",
        "            try:\n",
        "                q = input(\"\\nQuestion: \").strip()\n",
        "                if q.lower() in (\"quit\", \"exit\", \"q\"):\n",
        "                    break\n",
        "                if not q:\n",
        "                    continue\n",
        "                print(\"\\nThinking...\")\n",
        "                answer = self.query(q)\n",
        "                print(f\"\\nAnswer: {answer}\")\n",
        "            except KeyboardInterrupt:\n",
        "                print(\"\\nGoodbye!\")\n",
        "                break\n",
        "\n",
        "\n",
        "def main():\n",
        "    import argparse\n",
        "\n",
        "    parser = argparse.ArgumentParser(\n",
        "        description=\"RAG Document Question Answering System\"\n",
        "    )\n",
        "    parser.add_argument(\n",
        "        \"data_dir\",\n",
        "        nargs=\"?\",\n",
        "        default=\"data\",\n",
        "        help=\"Directory containing PDF/TXT documents (default: 'data')\",\n",
        "    )\n",
        "    parser.add_argument(\n",
        "        \"--reindex\",\n",
        "        action=\"store_true\",\n",
        "        help=\"Force reindexing even if vector store exists\",\n",
        "    )\n",
        "    parser.add_argument(\n",
        "        \"--query\", \"-q\",\n",
        "        help=\"Single query to run (non-interactive mode)\",\n",
        "    )\n",
        "    parser.add_argument(\n",
        "        \"--debug\", \"-d\",\n",
        "        action=\"store_true\",\n",
        "        help=\"Show retrieved contexts\",\n",
        "    )\n",
        "\n",
        "    args = parser.parse_args()\n",
        "\n",
        "    rag = RAGSystem(force_reindex=args.reindex, debug=args.debug)\n",
        "    rag.index_documents(args.data_dir)\n",
        "\n",
        "    if args.query:\n",
        "        answer = rag.query(args.query)\n",
        "        print(answer)\n",
        "    else:\n",
        "        rag.interactive()\n",
        "\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    main()\n"
      ]
    }
  ]
}